[workspace]
authors = ["jamesharden122 <loudonvillewf@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "read_bin"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025111005,<0.26"

